"""empty message

Revision ID: 6d0679cbabce
Revises: 
Create Date: 2021-03-22 16:46:19.096981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0679cbabce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('No. of Rooms', sa.String(length=3), nullable=True),
    sa.Column('No. of Bathrooms', sa.String(length=3), nullable=True),
    sa.Column('Price', sa.String(length=7), nullable=True),
    sa.Column('Property Type', sa.String(length=9), nullable=True),
    sa.Column('Location', sa.String(length=80), nullable=True),
    sa.Column('Photo Name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
