"""empty message

Revision ID: ce5ff77d6f22
Revises: 6d0679cbabce
Create Date: 2021-03-23 12:07:19.820328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5ff77d6f22'
down_revision = '6d0679cbabce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'Price',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=12),
               existing_nullable=True)
    op.alter_column('properties', 'Title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'Title',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('properties', 'Price',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
