"""empty message

Revision ID: e45f486fac97
Revises: ce5ff77d6f22
Create Date: 2021-03-23 18:38:43.414813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45f486fac97'
down_revision = 'ce5ff77d6f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'Description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'Description',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
